extraction:
  cpp:
    after_prepare: 
      - python report.py 63
  cobol:
    after_prepare: 
      - python report.py 63
  csharp:
    after_prepare: 
      - python report.py 63
  java:
    after_prepare: 
      - python report.py 63
  javascript:
    after_prepare: 
      - python report.py 63
  python:
    after_prepare: 
      - python report.py 63
